spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manojk?createDatabaseIfNotExist=true
    username: root
    password: manoj08387

  jpa:
    hibernate.ddl-auto: update
    show-sql: true

book:
  return:
    max:
      allowedDays: 10
server:
  port: 9090
